#include "./../../sequence/seq.hpp"
#include "./../../linear_align/linear_align.hpp"
#include <iostream>

using namespace std;

int main() {
    
    Seq seq1("seq1", "ggccaaguuuuuaagggcgcacgguggaugccuuggcaccaggaaccgaugaaggacgugggaggccacgauaguccccggggagccgucaaccaggcuuugauccggggguuuccgaauggggaaacccggcagucgucaugggcugucacccgcugcugaacacauaggcaguguggagggaacgcggggaagugaaacaucucaguacccgcaggaagagaaaacaaccgugauuccgggaguaguggcgagcgaaaccggaugaggccaaaccguauacgugugagacccggcagggguugcgugugcgggguugugggaucucucuuucacagucugccggcugugaggcgagucagaaaccguugauguaggcgaaggacaugcgaaagguccggcguagaggguaagacccccguagucgaaacaucagcggcucguuugagagacacccaaguagcacggggcccgagaaaucccgugugaaucuggcgggaccacccgcuaagccuaaauauucccuggugaccgauagcggauaguaccgugagggaauggugaaaaguaccgcgggagcggagugaaauaguaccugaaaccgugugccuacaagccgugggagcgucggacaucaagcuugcuuggugucucgugacugcgugccuuuugaagaaugagccugcgaguuugcgguguguugcgagguuaacccgaguggggaagccguagcgaaagcgaguccgaauagggcguuucaguagcacgcucaagacccgaagcggagugaucuagccaugggcagguugaagcggagguaagacuucguggaggaccgaacccaccaggguugaaaaccugggggaugaccugugguuaggggugaaaggccaaucaaacuccgugauagcugguucuccccgaaaugcauuuaggugcagcgucguguguuucuugccggagguagagcacuggauaggcgaugggcccuaccggguuacugaccuuagccaaacuccgaaugccgguaagugagagcgcggcagugagacugugggggauaagcuccauggucgagagggaaacagcccagagcaucgacuaaggccccuaagcguacgcuaagugggaaaggauguggagucgcacagacaaccaggagguuggcuuagaagcagccacccuugaaagagugcguaauagcucacuggucuagugauuccgcgccgacaauguagcggggcucaagcguaccgccgaagucgugucauucauacauuagggccaacgccuguauggauggguaggggagcgucgugugccgggugaagcagccgcggaagcgaguuguggacgguucacgagugagaaugcaggcaugaguagcgauacaaacgugagaaacguuugcgccgauugacuaaggguuccugggucaagcugaucugcccaggguaagucgggaccuaaggcgaggccgacaggcguagucgauggauaaccgguugauauuccgguacccgcugugaagcgucaaacaucgagcaucgugaugcuaaggccgugaagccgcccugaucucuucggaguugaggggagugguggagccgccggaccaagcgguuaguaggugagugauggggugacgcaggaagguaguccaucccggcgugguugucccgggguaagguguaggccgugcgguagguaaauccgucgcacacaaggcugagaccugaugccgagccgauuguggugaaguggaugauccuaugcugucgagaaaagccucuagcgaguuucauggcggcccguacccuaaaccgacucagguggucagguagagaauaccgaggcguucgggugaacuaugguuaaggaacucggcaaaaugcccccguaacuucgggagaaggggggccacaccuggugaugaucuuuacggucugagcuggggguggccgcagagaccagcgagaagcgacuguuuacuaaaaacacagguccgugcgaagccguaaggcgauguauacggacugacgccugcccggugcuggaacguuaaggggaccgguuagcuccauuucgguggggcgaagcugagaacuuaagcgccaguaaacggcggugguaacuauaaccauccuaagguagcgaaauuccuugucggguaaguuccgaccugcacgaauggcguaacgacuucucgacugucucaaccauaggcccggugaaauugcacuacgaguaaagaugcucguuucgcgcagcaggacggaaagaccccgggaccuuuacuacaguuugauauugguguucgguucggcuuguguaggauagcugggagacuuugaagcucgcacgccaguguggguggagucgucguugaaauaccagucuggucgugcuggaugucuaaccuggguccgugauccggaucagggacagugucugauggguaguuuaacuggggcgguugccuccuaaagaguaacggaggcgcccaaagguucccucagccugguuggcaaucagguguugaguguaagugcacaagggagcuugacugugagaccgacgggucgagcagggacgaaagucgggacuagugauccggcgguggcuuguggaagcgccgucgcucaacggauaaaagguaccccggggauaacaggcugaucuuccccaagaguccauaucgacgggaugguuuggcaccucgaugucggcucgucgcauccuggggcuggagucggucccaaggguugggcuguucgcccauuaaagcgguacgcgagcuggguuuagaacgucgugagacaguucggucccuauccgcugugcgcguaggagucuugagaagggcugucccuaguacgagaggaccgggacggacgaaccucuggugugccaguuguccugccaagggcauggcugguuggcuacguucgggagggauaaccgcugaaagcaucuaagcgggaagccugcuucgagaugaggacucccacccccuugagggguuaaggcucccaguagacgacuggguugauaggccggaucuggaagcaccgcaagguguggaggugaccgguacuaauaggccgagggcuuguccuc");
    Seq seq2("seq2", "gugaaaguuuccaagggcgcaugguggaugccuuggcaacaggagccgaagaaggacgugggaaucugcgauaagccugguggagucgauaaccggacguugagaccaggauuuccgaauggggaaaccccgcacgacgugucgugugacccccgguugaacacauaggccggguggagggaacguggggaacugaaacaucucaguacccacaggaagagaaaacaaaagugauuccguuaguaguggcgagcgaacgcggauggggcuaaaccguaugugugugauacccggcagggguugcaugugcgguguugugggccccuccuugucaugucugccggcauggcgcagugaggugcgggcauauagacgaaccaguguggaugcuggaccguagagggugagagucccguagucgaaauguguuccgccgcuguuggaggguugcccgaguagcacggggcccgaggaaucccgugugaaucugccaggaccaccugguaagccugaauacuaccuguugaccgauagcggaucaguaccgugagggaauggugaaaaguaccccgggaggggagugaaauaguaccugaaaccaugugccuacaaaccguuggagccuccuuguggggugacagcgugccuuuugaagaaugagccugcgaguuagugauacguggcgagguuaacccguguggggaagccguagcgaaagcgagucugaauagggcgauugagucgcguguccuagacccgaagcggagugaucuacccauggccagguugaagcgcguguaagaacgcguggaggaccgaacccacuucaguugaaaauggaggggaugaguuguggguaggggugaaaggccaaucaaacuccgugauagcugguucuccccgaaaugcauuuaggugcagcgucacguguuucuucccggagguagagcuacuggauggacgaugggcccuacaagggcuacugacuucagccaaacuccgaaugccgggaagugagagcguggcagugagacugugggggauaagcuucauagucgagagggaaacagcccagaccaccgguuaaggccccuaagcgugugcuaagugggaaaggauguggaguugcugagacaaccaggagguuggcuuagaagcagccacccuugaaagagugcguaauagcucacuggucaagugauuccgcgccgacaauguagcggggcucaaguacaccgccgaaaccguggcauucaguuuugcuggauggguaggggagcgucguucacgaggugaagccagcggguaacuucugguggauuguggacgagugagaaugcaggcaugaguagcgaaagacgggugagaaacccguccgccggaugacuaaggguuccagggucaagcuaaucugcccuggguaagucgggaccuaaggcgaggccgacaggcguagucgauggacaacggguugauauucccguaccagugaagaaccgcccaugcugagccggugauacuaaccgcccgaaccaucccgaaccucgucuuugacggggucggugauggggagcgcgggaccugaaccggggaggcaagcgcauuaacaggugugacgcaggaagguagccgggccgggcaauggaaaugaccuggucuaaggguguagggcugccgguagguaaauccgccggcuguaugccugagaccugaugggcgcccacauggugggugauccggugauccuaugcugccuagaaaagcaucggcgcgagguucaaacugcccguacccuaaaccgacacagguggucaggucagagaauacuaaggcgaucgagagaaucaugguuaaggaacucggcaaaaugcccccguaacuucgggagaaggggggccccaaccuugagcaccacgugcuggugugaggggaucggggccgcagagaccagggggaagcgacuguuuaucaaaaacacagguccaugcgaagucguaagacgauguauauggacugacuccugcccggugcuggaagguuaaggggacccguuagcuucggcgaagcggagaacuuaagccccaguaaacggcggugguaacuauaaccauccuaagguagcgaaauuccuugucggguaaguuccgaccugcacgaauggaguaacgacuuccccgcugucucaaccaugaacucggcgaaauugcauuacgaguaaagaugcucguuacgcgcagaaggacggaaagaccccgugaccuuuacuauaguuugguauugguguucgguguggcuuguguaggauaggugggagacugugaagcgggcacgccaguguucguggagucgucguugaaauaccacucuggucacucuggauaucuaacuucggcccgugauccgggucagggacagugccugauggguaguuuaacuggggcgguugccuccuaaaauguaacggaggcgcccaaagguucccucagccugguugguaaucaggugucgagugcaagugcacaagggagcuugacugugagaguggcagcucgagcagggacgaaagucgggacuagugauccggcggcucguuguggaacggccgucgcucaacggauaaaagguaccucggggauaacaggcugaucuugcccaagaguccauaucgacggcauguuuggcaccucgaugucggcucgucgcauccuggggcuggaguaggucccaaggguugggcuguucgcccauuaaagcgguacgcgagcuggguucagaacgucgugagacaguucggucccuauccucugcgcgcguuggaaauuugagaaggucugucccuaguacgagaggaccgggacggacgaaccucugguaugucaguuguaccgccaggugcauggcugauuagcuacguucgggauggauaaccgcugaaagcaucuaagcgggaagccggcuucgagaugagauuuccuugccccuuugagggugugaggcccccagcuagaacacuggguugauaggcuggauguggaagcgaggacugaagacucgugaagcugaccaguacuaauaggccgaugacuuacacaca");

    // Seq seq1("seq1", "CCCAAAGGG");
    // Seq seq2("seq2", "GGGAAACCC");

    seq1.set_encoding(nuc_encoding_scheme);
    seq2.set_encoding(nuc_encoding_scheme);
    LinearAlign linear_align(&seq1, &seq2);
    linear_align.compute_inside();
    linear_align.compute_outside();
    // linear_align.run_backward_phase(false);
    // linear_align.print_beam();

    linear_align.print_alpha_beta();


    // print alignment
    // linear_align.traceback();

    return 0;
}

// "--"
// "AC"


