#include "./../../sequence/seq.hpp"
#include "./../../sequence/multi_seq.hpp"
#include "./../../linear_align/linear_align.hpp"
#include <iostream>

using namespace std;

int main() {
    
    Seq seq1("seq1", "ggccaaguuuuuaagggcgcacgguggaugccuuggcaccaggaaccgaugaaggacgugggaggccacgauaguccccggggagccgucaaccaggcuuugauccggggguuuccgaauggggaaacccggcagucgucaugggcugucacccgcugcugaacacauaggcaguguggagggaacgcggggaagugaaacaucucaguacccgcaggaagagaaaacaaccgugauuccgggaguaguggcgagcgaaaccggaugaggccaaaccguauacgugugagacccggcagggguugcgugugcgggguugugggaucucucuuucacagucugccggcugugaggcgagucagaaaccguugauguaggcgaaggacaugcgaaagguccggcguagaggguaagacccccguagucgaaacaucagcggcucguuugagagacacccaaguagcacggggcccgagaaaucccgugugaaucuggcgggaccacccgcuaagccuaaauauucccuggugaccgauagcggauaguaccgugagggaauggugaaaaguaccgcgggagcggagugaaauaguaccugaaaccgugugccuacaagccgugggagcgucggacaucaagcuugcuuggugucucgugacugcgugccuuuugaagaaugagccugcgaguuugcgguguguugcgagguuaacccgaguggggaagccguagcgaaagcgaguccgaauagggcguuucaguagcacgcucaagacccgaagcggagugaucuagccaugggcagguugaagcggagguaagacuucguggaggaccgaacccaccaggguugaaaaccugggggaugaccugugguuaggggugaaaggccaaucaaacuccgugauagcugguucuccccgaaaugcauuuaggugcagcgucguguguuucuugccggagguagagcacuggauaggcgaugggcccuaccggguuacugaccuuagccaaacuccgaaugccgguaagugagagcgcggcagugagacugugggggauaagcuccauggucgagagggaaacagcccagagcaucgacuaaggccccuaagcguacgcuaagugggaaaggauguggagucgcacagacaaccaggagguuggcuuagaagcagccacccuugaaagagugcguaauagcucacuggucuagugauuccgcgccgacaauguagcggggcucaagcguaccgccgaagucgugucauucauacauuagggccaacgccuguauggauggguaggggagcgucgugugccgggugaagcagccgcggaagcgaguuguggacgguucacgagugagaaugcaggcaugaguagcgauacaaacgugagaaacguuugcgccgauugacuaaggguuccugggucaagcugaucugcccaggguaagucgggaccuaaggcgaggccgacaggcguagucgauggauaaccgguugauauuccgguacccgcugugaagcgucaaacaucgagcaucgugaugcuaaggccgugaagccgcccugaucucuucggaguugaggggagugguggagccgccggaccaagcgguuaguaggugagugauggggugacgcaggaagguaguccaucccggcgugguugucccgggguaagguguaggccgugcgguagguaaauccgucgcacacaaggcugagaccugaugccgagccgauuguggugaaguggaugauccuaugcugucgagaaaagccucuagcgaguuucauggcggcccguacccuaaaccgacucagguggucagguagagaauaccgaggcguucgggugaacuaugguuaaggaacucggcaaaaugcccccguaacuucgggagaaggggggccacaccuggugaugaucuuuacggucugagcuggggguggccgcagagaccagcgagaagcgacuguuuacuaaaaacacagguccgugcgaagccguaaggcgauguauacggacugacgccugcccggugcuggaacguuaaggggaccgguuagcuccauuucgguggggcgaagcugagaacuuaagcgccaguaaacggcggugguaacuauaaccauccuaagguagcgaaauuccuugucggguaaguuccgaccugcacgaauggcguaacgacuucucgacugucucaaccauaggcccggugaaauugcacuacgaguaaagaugcucguuucgcgcagcaggacggaaagaccccgggaccuuuacuacaguuugauauugguguucgguucggcuuguguaggauagcugggagacuuugaagcucgcacgccaguguggguggagucgucguugaaauaccagucuggucgugcuggaugucuaaccuggguccgugauccggaucagggacagugucugauggguaguuuaacuggggcgguugccuccuaaagaguaacggaggcgcccaaagguucccucagccugguuggcaaucagguguugaguguaagugcacaagggagcuugacugugagaccgacgggucgagcagggacgaaagucgggacuagugauccggcgguggcuuguggaagcgccgucgcucaacggauaaaagguaccccggggauaacaggcugaucuuccccaagaguccauaucgacgggaugguuuggcaccucgaugucggcucgucgcauccuggggcuggagucggucccaaggguugggcuguucgcccauuaaagcgguacgcgagcuggguuuagaacgucgugagacaguucggucccuauccgcugugcgcguaggagucuugagaagggcugucccuaguacgagaggaccgggacggacgaaccucuggugugccaguuguccugccaagggcauggcugguuggcuacguucgggagggauaaccgcugaaagcaucuaagcgggaagccugcuucgagaugaggacucccacccccuugagggguuaaggcucccaguagacgacuggguugauaggccggaucuggaagcaccgcaagguguggaggugaccgguacuaauaggccgagggcuuguccuc");
    Seq seq2("seq2", "gugaaaguuuccaagggcgcaugguggaugccuuggcaacaggagccgaagaaggacgugggaaucugcgauaagccugguggagucgauaaccggacguugagaccaggauuuccgaauggggaaaccccgcacgacgugucgugugacccccgguugaacacauaggccggguggagggaacguggggaacugaaacaucucaguacccacaggaagagaaaacaaaagugauuccguuaguaguggcgagcgaacgcggauggggcuaaaccguaugugugugauacccggcagggguugcaugugcgguguugugggccccuccuugucaugucugccggcauggcgcagugaggugcgggcauauagacgaaccaguguggaugcuggaccguagagggugagagucccguagucgaaauguguuccgccgcuguuggaggguugcccgaguagcacggggcccgaggaaucccgugugaaucugccaggaccaccugguaagccugaauacuaccuguugaccgauagcggaucaguaccgugagggaauggugaaaaguaccccgggaggggagugaaauaguaccugaaaccaugugccuacaaaccguuggagccuccuuguggggugacagcgugccuuuugaagaaugagccugcgaguuagugauacguggcgagguuaacccguguggggaagccguagcgaaagcgagucugaauagggcgauugagucgcguguccuagacccgaagcggagugaucuacccauggccagguugaagcgcguguaagaacgcguggaggaccgaacccacuucaguugaaaauggaggggaugaguuguggguaggggugaaaggccaaucaaacuccgugauagcugguucuccccgaaaugcauuuaggugcagcgucacguguuucuucccggagguagagcuacuggauggacgaugggcccuacaagggcuacugacuucagccaaacuccgaaugccgggaagugagagcguggcagugagacugugggggauaagcuucauagucgagagggaaacagcccagaccaccgguuaaggccccuaagcgugugcuaagugggaaaggauguggaguugcugagacaaccaggagguuggcuuagaagcagccacccuugaaagagugcguaauagcucacuggucaagugauuccgcgccgacaauguagcggggcucaaguacaccgccgaaaccguggcauucaguuuugcuggauggguaggggagcgucguucacgaggugaagccagcggguaacuucugguggauuguggacgagugagaaugcaggcaugaguagcgaaagacgggugagaaacccguccgccggaugacuaaggguuccagggucaagcuaaucugcccuggguaagucgggaccuaaggcgaggccgacaggcguagucgauggacaacggguugauauucccguaccagugaagaaccgcccaugcugagccggugauacuaaccgcccgaaccaucccgaaccucgucuuugacggggucggugauggggagcgcgggaccugaaccggggaggcaagcgcauuaacaggugugacgcaggaagguagccgggccgggcaauggaaaugaccuggucuaaggguguagggcugccgguagguaaauccgccggcuguaugccugagaccugaugggcgcccacauggugggugauccggugauccuaugcugccuagaaaagcaucggcgcgagguucaaacugcccguacccuaaaccgacacagguggucaggucagagaauacuaaggcgaucgagagaaucaugguuaaggaacucggcaaaaugcccccguaacuucgggagaaggggggccccaaccuugagcaccacgugcuggugugaggggaucggggccgcagagaccagggggaagcgacuguuuaucaaaaacacagguccaugcgaagucguaagacgauguauauggacugacuccugcccggugcuggaagguuaaggggacccguuagcuucggcgaagcggagaacuuaagccccaguaaacggcggugguaacuauaaccauccuaagguagcgaaauuccuugucggguaaguuccgaccugcacgaauggaguaacgacuuccccgcugucucaaccaugaacucggcgaaauugcauuacgaguaaagaugcucguuacgcgcagaaggacggaaagaccccgugaccuuuacuauaguuugguauugguguucgguguggcuuguguaggauaggugggagacugugaagcgggcacgccaguguucguggagucgucguugaaauaccacucuggucacucuggauaucuaacuucggcccgugauccgggucagggacagugccugauggguaguuuaacuggggcgguugccuccuaaaauguaacggaggcgcccaaagguucccucagccugguugguaaucaggugucgagugcaagugcacaagggagcuugacugugagaguggcagcucgagcagggacgaaagucgggacuagugauccggcggcucguuguggaacggccgucgcucaacggauaaaagguaccucggggauaacaggcugaucuugcccaagaguccauaucgacggcauguuuggcaccucgaugucggcucgucgcauccuggggcuggaguaggucccaaggguugggcuguucgcccauuaaagcgguacgcgagcuggguucagaacgucgugagacaguucggucccuauccucugcgcgcguuggaaauuugagaaggucugucccuaguacgagaggaccgggacggacgaaccucugguaugucaguuguaccgccaggugcauggcugauuagcuacguucgggauggauaaccgcugaaagcaucuaagcgggaagccggcuucgagaugagauuuccuugccccuuugagggugugaggcccccagcuagaacacuggguugauaggcuggauguggaagcgaggacugaagacucgugaagcugaccaguacuaauaggccgaugacuuacacaca");

    // Seq seq1("seq1", "ugcuuggcgaccauagcguuauggacccaccugaucccaugccgaacucaguagugaaacguaauagcgccgaugguaguguggggucuccccaugugagaguaggacaucgccaggcau");
    // Seq seq2("seq2", "ccgggugccuauaccggaggggccacacccguucccauuccgaacacggucguuaagcccuccagggccgaugguacuggggcguuaccgcccugggagaguaggucggugcccggg");
    // Seq seq1("seq1", "CCCAAAGGG");
    // Seq seq2("seq2", "GGGAAACCCG");

    seq1.set_encoding(nuc_encoding_scheme);
    seq2.set_encoding(nuc_encoding_scheme);
    LinearAlign linear_align(&seq1, &seq2);
    linear_align.reset_beams();
    linear_align.prob_set1();
    
    linear_align.compute_inside(true, 100, true);
    linear_align.print_alpha_beta();
    MultiSeq multiseq = linear_align.get_alignment();
    float similarity = multiseq.get_seq_identity();
    multiseq.print_sequences();

    linear_align.reset_beams();
    linear_align.prob_set2(similarity);
    linear_align.compute_inside(false, 100, true);
    linear_align.compute_outside();
    linear_align.compute_coincidence_probabilities();
    linear_align.print_alpha_beta();


    return 0;
}
// "--"
// "AC"


