#include "./../../partition/partition.hpp"
#include <iostream>

using namespace std;

int main() {
    cout << "Hello, World!" << endl;


    Seq seq1("seq1", "ggccaaguuuuuaagggcgcacgguggaugccuuggcaccaggaaccgaugaaggacgugggaggccacgauaguccccggggagccgucaaccaggcuuugauccggggguuuccgaauggggaaacccggcagucgucaugggcugucacccgcugcugaacacauaggcaguguggagggaacgcggggaagugaaacaucucaguacccgcaggaagagaaaacaaccgugauuccgggaguaguggcgagcgaaaccggaugaggccaaaccguauacgugugagacccggcagggguugcgugugcgggguugugggaucucucuuucacagucugccggcugugaggcgagucagaaaccguugauguaggcgaaggacaugcgaaagguccggcguagaggguaagacccccguagucgaaacaucagcggcucguuugagagacacccaaguagcacggggcccgagaaaucccgugugaaucuggcgggaccacccgcuaagccuaaauauucccuggugaccgauagcggauaguaccgugagggaauggugaaaaguaccgcgggagcggagugaaauaguaccugaaaccgugugccuacaagccgugggagcgucggacaucaagcuugcuuggugucucgugacugcgugccuuuugaagaaugagccugcgaguuugcgguguguugcgagguuaacccgaguggggaagccguagcgaaagcgaguccgaauagggcguuucaguagcacgcucaagacccgaagcggagugaucuagccaugggcagguugaagcggagguaagacuucguggaggaccgaacccaccaggguugaaaaccugggggaugaccugugguuaggggugaaaggccaaucaaacuccgugauagcugguucuccccgaaaugcauuuaggugcagcgucguguguuucuugccggagguagagcacuggauaggcgaugggcccuaccggguuacugaccuuagccaaacuccgaaugccgguaagugagagcgcggcagugagacugugggggauaagcuccauggucgagagggaaacagcccagagcaucgacuaaggccccuaagcguacgcuaagugggaaaggauguggagucgcacagacaaccaggagguuggcuuagaagcagccacccuugaaagagugcguaauagcucacuggucuagugauuccgcgccgacaauguagcggggcucaagcguaccgccgaagucgugucauucauacauuagggccaacgccuguauggauggguaggggagcgucgugugccgggugaagcagccgcggaagcgaguuguggacgguucacgagugagaaugcaggcaugaguagcgauacaaacgugagaaacguuugcgccgauugacuaaggguuccugggucaagcugaucugcccaggguaagucgggaccuaaggcgaggccgacaggcguagucgauggauaaccgguugauauuccgguacccgcugugaagcgucaaacaucgagcaucgugaugcuaaggccgugaagccgcccugaucucuucggaguugaggggagugguggagccgccggaccaagcgguuaguaggugagugauggggugacgcaggaagguaguccaucccggcgugguugucccgggguaagguguaggccgugcgguagguaaauccgucgcacacaaggcugagaccugaugccgagccgauuguggugaaguggaugauccuaugcugucgagaaaagccucuagcgaguuucauggcggcccguacccuaaaccgacucagguggucagguagagaauaccgaggcguucgggugaacuaugguuaaggaacucggcaaaaugcccccguaacuucgggagaaggggggccacaccuggugaugaucuuuacggucugagcuggggguggccgcagagaccagcgagaagcgacuguuuacuaaaaacacagguccgugcgaagccguaaggcgauguauacggacugacgccugcccggugcuggaacguuaaggggaccgguuagcuccauuucgguggggcgaagcugagaacuuaagcgccaguaaacggcggugguaacuauaaccauccuaagguagcgaaauuccuugucggguaaguuccgaccugcacgaauggcguaacgacuucucgacugucucaaccauaggcccggugaaauugcacuacgaguaaagaugcucguuucgcgcagcaggacggaaagaccccgggaccuuuacuacaguuugauauugguguucgguucggcuuguguaggauagcugggagacuuugaagcucgcacgccaguguggguggagucgucguugaaauaccagucuggucgugcuggaugucuaaccuggguccgugauccggaucagggacagugucugauggguaguuuaacuggggcgguugccuccuaaagaguaacggaggcgcccaaagguucccucagccugguuggcaaucagguguugaguguaagugcacaagggagcuugacugugagaccgacgggucgagcagggacgaaagucgggacuagugauccggcgguggcuuguggaagcgccgucgcucaacggauaaaagguaccccggggauaacaggcugaucuuccccaagaguccauaucgacgggaugguuuggcaccucgaugucggcucgucgcauccuggggcuggagucggucccaaggguugggcuguucgcccauuaaagcgguacgcgagcuggguuuagaacgucgugagacaguucggucccuauccgcugugcgcguaggagucuugagaagggcugucccuaguacgagaggaccgggacggacgaaccucuggugugccaguuguccugccaagggcauggcugguuggcuacguucgggagggauaaccgcugaaagcaucuaagcgggaagccugcuucgagaugaggacucccacccccuugagggguuaaggcucccaguagacgacuggguugauaggccggaucuggaagcaccgcaagguguggaggugaccgguacuaauaggccgagggcuuguccuc");


    // Seq seq1("seq1", "CCCAAAGGG");
    // Seq seq1("seq1", "GCCGAGCCAGGUAGCGUUGGCUUGUCACCCGAGCGGGGGCAAUAAGGUGGUGUUGGAUGCCUGGUCGUUUGCGCUUGGGGUCUGCGCCUGUGGUUUGCACUAUGCGGCCCGCCCGUUCCAAGUUGCGUAGCGUGUGUGGGGCGCCUGGGCGAAGGCUCGAGCGUCCCUGCACCUAGAGUGGCGGGUAUUGCGUGAGGCUGGUUUCACAGAGCAGCGAGUACCGCCCGCUUCCAACGGUGGAAGGAUAACGGGCCGCUGCAGCCCUGGCCCGCUUCCGGCCCAAGUGCCUUCCAUGGCAGACCACCACCUUU");

    // Seq seq1("seq1", "AAAACGGUCCUUAUCAGGACCAAACA");


    unordered_map <char, int> scheme = {{'A', 1}, {'C', 2}, {'G', 3}, {'U', 4}};


    // print the sequence
    cout << "Sequence: " << seq1.get_sequence() << endl;
    Partition inside(seq1, *(new EnergyModel(EnergyParamsType::VIENNA)), InsideMode::PARTITION);
    inside.print_alpha_beta();
    // inside.print_mfe_structure();
    cout << "Ensemble Energy: " << inside.get_ensemble_energy() << endl;


    // inside.debug_states();
    inside.lazy_outside();
    inside.print_alpha_beta();
    // inside.debug_states();

    return 0;
}